version: "3.9"
services:

  db:
    restart: always
    container_name: postgres_db
    image: postgres:16.3-alpine 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5434:5432

  redis:
    container_name: redis_db
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@password.com
      - PGADMIN_DEFAULT_PASSWORD=password

volumes:
  postgres_data:

networks:
  default:
    driver: bridge