# Generated by Django 4.2.1 on 2024-04-25 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0011_uploadfilesform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadFilesForm',
            new_name='UploadFiles',
        ),
    ]
